In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.read_csv('../seeds/_seeds_setup/raw_streaming__subscriptions.csv')
df.head()

,subscription_id,user_id,plan_type,status,start_date,start_time,end_date,end_time,monthly_fee_cents,updated_at
0,sub_0352,usr_848,BASIC,Cancelled,2022-11-15,00:05:21,2023-01-30,02:58:30,599,2023-02-02 09:48:00
1,sub_0202,usr_537,standard,CANCELLED,2020-05-08,20:46:47,2021-03-09,05:36:40,875,2021-03-10 22:22:00
2,sub_0105,usr_506,PREMIUM,cancelled,2024-06-10,21:39:17,2024-06-21,16:00:27,1312,2024-06-26 05:07:00
3,sub_0277,usr_268,Basic,Cancelled,2023-07-04,10:03:06,2024-04-10,07:42:13,525,2024-04-13 00:44:00
4,sub_0179,usr_677,basic,active,2024-04-18,01:32:16,NaN,NaN,525,2024-04-19 23:55:00

In [3]:
staff_ids = pd.read_csv('staff_member_user_ids.csv')['user_id']

In [4]:
(
    df
    .assign(fix_plan_type = lambda df: df['plan_type'].str.lower())
    .assign(staff_flag = lambda df: df['user_id'].isin(staff_ids))
.groupby(['fix_plan_type', 'monthly_fee_cents'])
.agg(
    staff = ('staff_flag', 'sum'),
    nonstaff = ('staff_flag', lambda col: col.size - col.sum()),
    all = ('staff_flag', lambda col: col.size),
)
)

                                 staff  nonstaff  all
fix_plan_type monthly_fee_cents
basic         525                   38         0   38
              599                    1       134  135
premium       1312                  30         0   30
              1499                   2       125  127
standard      875                   36         3   39
              999                    0       134  134